### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by madhur**
Few fixes which I had to do to make it work on my system.

### CODE REVIEW

**Comment by Amitabha37377** [comment]
Thanks for the fixes and sorry for my carelessness

**Comment by madhur** [comment]
Thank you for the work on this great setup.

I was curious how the DND widget works. I tried enabling and it doesn't seem to have any effect. A test `notify-send` was received immediately. Am I missing something?

**Comment by Amitabha37377** [comment]
I fixed it in the recent commit, you can check it now.

**Comment by madhur** [comment]
Thats great. The commit is too big, https://github.com/Amitabha37377/Awful-DOTS/commit/40a6aaedab44caf6aa7f063c9590eff19f8db5fc

Can you point me to the diff so that I can just directly apply it in my version?

**Pull request merged**
